# Generated by Django 3.1.2 on 2021-02-09 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planset',
            options={'ordering': ('build', 'path'), 'verbose_name': 'Set di planimetrie', 'verbose_name_plural': 'Set di planimetrie'},
        ),
        migrations.AlterField(
            model_name='building',
            name='zoom',
            field=models.FloatField(default=10, help_text='Massimo intorno a 23', verbose_name='Fattore di zoom'),
        ),
        migrations.AlterField(
            model_name='planset',
            name='intro',
            field=models.CharField(blank=True, help_text='Poche parole per descrivere il set', max_length=100, null=True, verbose_name='Descrizione'),
        ),
        migrations.AlterField(
            model_name='planset',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Scegli bene, può essere modificato solo in amministrazione', null=True, on_delete=django.db.models.deletion.SET_NULL, to='buildings.planset', verbose_name='Set genitore'),
        ),
        migrations.AlterField(
            model_name='planset',
            name='plans',
            field=models.ManyToManyField(blank=True, help_text='Scegli le planimetrie da mostrare in questo set', to='buildings.Plan', verbose_name='Planimetrie'),
        ),
        migrations.AlterField(
            model_name='planset',
            name='title',
            field=models.CharField(help_text='Nome del set', max_length=50, verbose_name='Titolo'),
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(help_text='Family name', max_length=50, verbose_name='Titolo')),
                ('intro', models.CharField(blank=True, help_text='Few words to describe the family', max_length=100, null=True, verbose_name='Descrizione')),
                ('slug', models.SlugField(editable=False, max_length=100, null=True)),
                ('sheet', models.JSONField(blank=True, help_text='A dictionary of element features', null=True, verbose_name='Data sheet')),
                ('parent', models.ForeignKey(blank=True, help_text='Scegli bene, può essere modificato solo in amministrazione', null=True, on_delete=django.db.models.deletion.SET_NULL, to='buildings.family', verbose_name='Parent family')),
            ],
            options={
                'verbose_name': 'Element Family',
                'verbose_name_plural': 'Element Families',
            },
        ),
    ]
