# Generated by Django 3.1.2 on 2021-02-09 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0002_auto_20210209_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='build',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='building_family', to='buildings.building', verbose_name='Edificio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='family',
            name='parent',
            field=models.ForeignKey(help_text='Scegli bene, può essere modificato solo in amministrazione', null=True, on_delete=django.db.models.deletion.CASCADE, to='buildings.family', verbose_name='Parent family'),
        ),
        migrations.AlterField(
            model_name='planset',
            name='parent',
            field=models.ForeignKey(help_text='Scegli bene, può essere modificato solo in amministrazione', null=True, on_delete=django.db.models.deletion.CASCADE, to='buildings.planset', verbose_name='Set genitore'),
        ),
    ]
