# Generated by Django 3.1.2 on 2021-03-16 19:05

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0005_auto_20210315_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(geography=True, null=True, srid=4326),
        ),
    ]
