# Generated by Django 3.1.2 on 2021-03-21 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0007_auto_20210316_2152'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanVisibility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visibility', models.BooleanField(default=False, help_text='Check if plan is visible in this plan set', verbose_name='Visibile')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_visibility', to='buildings.plan', verbose_name='Planimetria')),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planset_visibility', to='buildings.planset', verbose_name='Set di planimetrie')),
            ],
            options={
                'verbose_name': 'Plan visibility',
            },
        ),
    ]
