# Generated by Django 3.1.2 on 2021-03-21 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0008_planvisibility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planset',
            name='plans',
        ),
    ]
