# Generated by Django 3.1.2 on 2021-03-21 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0009_remove_planset_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='planset',
            name='plans',
            field=models.ManyToManyField(blank=True, help_text='Scegli le planimetrie da mostrare nel set', through='buildings.PlanVisibility', to='buildings.Plan', verbose_name='Planimetrie'),
        ),
    ]
