# Generated by Django 3.1.2 on 2021-03-28 20:01

import buildings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0010_planset_plans'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'Città', 'verbose_name_plural': 'Città'},
        ),
        migrations.AlterModelOptions(
            name='planvisibility',
            options={'verbose_name': 'Visibilità della planimetria'},
        ),
        migrations.AlterField(
            model_name='building',
            name='address',
            field=models.CharField(blank=True, help_text='Qualcosa tipo "Rome - Monteverde" va bene', max_length=100, null=True, verbose_name='Indirizzo'),
        ),
        migrations.AlterField(
            model_name='building',
            name='intro',
            field=models.CharField(default=buildings.models.building_default_intro, help_text='Qualche parola per descrivere questo edificio', max_length=100, verbose_name='Introduzione'),
        ),
        migrations.AlterField(
            model_name='building',
            name='lat',
            field=models.FloatField(null=True, verbose_name='Latitudine'),
        ),
        migrations.AlterField(
            model_name='building',
            name='long',
            field=models.FloatField(help_text='Coordinate da Google Maps\n            oppure https://openstreetmap.org', null=True, verbose_name='Longitudine'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='elev',
            field=models.FloatField(default=0, verbose_name='Livello in metri'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='refresh',
            field=models.BooleanField(default=True, verbose_name='Ripristina la geometria'),
        ),
        migrations.AlterField(
            model_name='planvisibility',
            name='visibility',
            field=models.BooleanField(default=True, help_text='Spunta se la planimetria è visibile in questo set', verbose_name='Visibile'),
        ),
    ]
