# Generated by Django 3.1.2 on 2021-03-30 12:23

import buildings.models
import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0011_auto_20210328_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='poly',
            field=django.contrib.gis.db.models.fields.PolygonField(null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='building',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default=buildings.models.building_default_location, geography=True, null=True, srid=4326),
        ),
    ]
