# Generated by Django 3.1.2 on 2021-03-30 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0012_auto_20210330_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='poly',
        ),
    ]
