# Generated by Django 3.1.2 on 2021-03-31 15:54

import colorfield.fields
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0013_remove_city_poly'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photostation',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
        migrations.CreateModel(
            name='PlanGeometry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', colorfield.fields.ColorField(default='#FF0000', max_length=18)),
                ('popup', models.CharField(help_text='Geometry description in popup', max_length=100, verbose_name='Popup')),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(help_text='can be LineString or Polygon', srid=4326, verbose_name='Geometry')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_geometry', to='buildings.plan', verbose_name='Plan geometry')),
            ],
            options={
                'verbose_name': 'Plan geometry',
                'verbose_name_plural': 'Plan geometries',
            },
        ),
    ]
