# Generated by Django 3.1.2 on 2021-04-14 21:25

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0015_auto_20210401_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='plangeometry',
            name='geometryz',
            field=django.contrib.gis.db.models.fields.GeometryField(dim=3, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='plangeometry',
            name='is3d',
            field=models.BooleanField(default=False, help_text='Use third dimension in camera view', verbose_name='Is 3D'),
        ),
    ]
