# Generated by Django 3.1.2 on 2021-06-22 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0017_auto_20210419_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='private',
            field=models.BooleanField(default=True, help_text='Can be viewed only by authenticated users', verbose_name='Private'),
        ),
    ]
