# Generated by Django 3.1.2 on 2021-08-14 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('buildings', '0019_journal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journal',
            options={'ordering': ('-date',), 'verbose_name': 'Giornale di cantiere', 'verbose_name_plural': 'Giornali di cantiere'},
        ),
        migrations.AddField(
            model_name='journal',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Autore'),
        ),
        migrations.AlterField(
            model_name='building',
            name='private',
            field=models.BooleanField(default=True, help_text='Può essere visto solo da utenti autenticati', verbose_name='Privato'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='build',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='building_journal', to='buildings.building', verbose_name='Edificio'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='title',
            field=models.CharField(help_text='Titolo del giornale di cantiere', max_length=50, verbose_name='Titolo'),
        ),
    ]
