# Generated by Django 3.1.2 on 2021-09-29 12:26

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0020_auto_20210814_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comuni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid', models.BigIntegerField()),
                ('gid2', models.BigIntegerField()),
                ('comune_bel', models.CharField(max_length=254)),
                ('avdicm', models.CharField(max_length=254)),
                ('classid', models.CharField(max_length=254)),
                ('comune_ist', models.CharField(max_length=254)),
                ('comune_com', models.CharField(max_length=100)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'verbose_name': 'Comune',
                'verbose_name_plural': 'Comuni',
            },
        ),
    ]
