# Generated by Django 3.1.2 on 2021-10-05 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0021_comuni'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comuni',
            options={'ordering': ('comune_com',), 'verbose_name': 'Comune', 'verbose_name_plural': 'Comuni'},
        ),
        migrations.AddField(
            model_name='planset',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
