# Generated by Django 3.1.2 on 2021-10-06 19:31

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0022_auto_20211005_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='comuni',
            name='geom_lo',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326),
        ),
    ]
