# Generated by Django 3.1.2 on 2021-10-16 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0023_comuni_geom_lo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comuni',
        ),
    ]
