# Generated by Django 3.1.2 on 2021-11-09 19:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0025_auto_20211106_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='cpg_file',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to='uploads/buildings/plans/shapes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['cpg'])], verbose_name='CPG file'),
        ),
        migrations.AddField(
            model_name='plan',
            name='dbf_file',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to='uploads/buildings/plans/shapes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['dbf'])], verbose_name='DBF file'),
        ),
        migrations.AddField(
            model_name='plan',
            name='prj_file',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to='uploads/buildings/plans/shapes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['prj'])], verbose_name='PRJ file'),
        ),
        migrations.AddField(
            model_name='plan',
            name='shp_file',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to='uploads/buildings/plans/shapes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['shp'])], verbose_name='SHP file'),
        ),
        migrations.AddField(
            model_name='plan',
            name='shx_file',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to='uploads/buildings/plans/shapes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['shx'])], verbose_name='SHX file'),
        ),
    ]
