# Generated by Django 3.1.2 on 2021-11-10 16:53

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0028_auto_20211110_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='dxfimport',
            name='color_field',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=18),
        ),
        migrations.AlterField(
            model_name='dxfimport',
            name='color',
            field=models.CharField(max_length=254),
        ),
    ]
