# Generated by Django 3.1.2 on 2021-11-12 23:06

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0029_auto_20211110_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='dxfimport',
            name='geometry',
            field=django.contrib.gis.db.models.fields.GeometryField(help_text='can be LineString or Polygon', null=True, srid=4326, verbose_name='Geometry'),
        ),
    ]
