# Generated by Django 3.1.2 on 2021-12-01 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('buildings', '0032_auto_20211201_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='visitor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Building visitor'),
        ),
    ]
