# Generated by Django 3.1.2 on 2021-12-10 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0033_auto_20211201_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='lat',
            field=models.FloatField(null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='city',
            name='long',
            field=models.FloatField(help_text='Coordinates from Google Maps\n            or https://openstreetmap.org', null=True, verbose_name='Longitude'),
        ),
    ]
