# Generated by Django 3.1.2 on 2022-01-15 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0035_auto_20220110_0723'),
    ]

    operations = [
        migrations.AddField(
            model_name='dxfimport',
            name='geomjson',
            field=models.JSONField(null=True),
        ),
    ]
