# Generated by Django 3.1.2 on 2022-01-27 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0037_auto_20220116_0940'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlanGeometry',
        ),
    ]
